/**
 * /api/protocol-watch
 * Proactive check: for every marker with history, has it gotten WORSE
 * — consistently, not just noise — since the user's active protocol started?
 *
 * This is the check that should have caught ApoB climbing from 84 to 154
 * across four readings after starting an Animal-Based protocol, instead of
 * requiring the user to notice it themselves by opening a chart.
 *
 * Trend detection is pure arithmetic (deterministic, not AI-judged) — only
 * the narrative explanation is generated by Claude, and only for markers
 * that already failed the numeric test. Cached per marker-set + protocol,
 * so a repeat dashboard load costs nothing until new data actually changes.
 */
import { sha256, hashMarkers, sbSelect, sbUpsert, sbUpdate, rateLimit, logUsage, json, callClaude } from './_lib.js';

export const config = { runtime: 'edge' };

// Markers where a LOWER value is the healthy direction.
const LOWER_IS_BETTER = [
  'apob', 'ldl', 'hba1c', 'fasting glucose', 'glucose', 'triglycerides',
  'crp', 'cortisol', 'homocysteine', 'il-6', 'insulin', 'visceral fat',
  'estrogen', 'systolic', 'diastolic', 'uric acid', 'ferritin high',
];
// Markers where a HIGHER value is the healthy direction.
const HIGHER_IS_BETTER = [
  'hdl', 'testosterone', 'vitamin d', 'dhea-s', 'igf-1', 'vo2', 'lean mass', 'shbg',
];
// Movement in these, if it fails the check, should say "talk to a doctor" —
// not "adjust your protocol." These are markers where sustained bad movement
// carries real near-term clinical risk rather than being purely a lifestyle lever.
const MEDICAL_ESCALATION = [
  'apob', 'ldl', 'hba1c', 'fasting glucose', 'triglycerides', 'systolic', 'diastolic', 'crp',
];

function directionFor(name) {
  const n = name.toLowerCase();
  if (LOWER_IS_BETTER.some(k => n.includes(k))) return 'lower';
  if (HIGHER_IS_BETTER.some(k => n.includes(k))) return 'higher';
  return null;
}
function isMedical(name) {
  const n = name.toLowerCase();
  return MEDICAL_ESCALATION.some(k => n.includes(k));
}

const WORSENING_THRESHOLD = 0.15; // 15% move against the person, minimum to flag

function detectFlags(markers, cycleStartedAt) {
  if (!cycleStartedAt) return [];
  const cutoff = cycleStartedAt.slice(0, 10);
  const flags = [];

  for (const m of markers || []) {
    const dir = directionFor(m.name || '');
    if (!dir) continue;
    const hist = (m.history || [])
      .filter(h => h.date && h.value !== undefined && h.value !== null && !isNaN(parseFloat(h.value)))
      .map(h => ({ date: h.date, value: parseFloat(h.value) }))
      .sort((a, b) => a.date.localeCompare(b.date));
    if (hist.length < 3) continue;

    const before = hist.filter(h => h.date <= cutoff);
    const after = hist.filter(h => h.date > cutoff);
    if (before.length === 0 || after.length < 2) continue; // need a real pre-protocol baseline + at least 2 readings since

    const baseline = before[before.length - 1];
    const latest = after[after.length - 1];
    const worstSinceStart = dir === 'lower'
      ? Math.max(...after.map(h => h.value))
      : Math.min(...after.map(h => h.value));

    // Only flag if the trend hasn't reversed — latest IS (at or near) the worst point since starting.
    const isStillWorsening = latest.value === worstSinceStart;
    if (!isStillWorsening) continue;

    const pctChange = baseline.value !== 0 ? (latest.value - baseline.value) / Math.abs(baseline.value) : 0;
    const badChange = dir === 'lower' ? pctChange : -pctChange;
    if (badChange < WORSENING_THRESHOLD) continue;

    flags.push({
      marker: m.name,
      unit: m.unit || '',
      direction: dir,
      baseline_date: baseline.date,
      baseline_value: baseline.value,
      latest_date: latest.date,
      latest_value: latest.value,
      pct_change: Math.round(badChange * 1000) / 10, // e.g. 45.3 (%)
      readings_since_start: after.length,
      severity: isMedical(m.name) ? 'physician' : 'protocol',
    });
  }
  // Worst offenders first
  return flags.sort((a, b) => b.pct_change - a.pct_change);
}

export default async function handler(req) {
  if (req.method !== 'POST') return new Response('Method not allowed', { status: 405 });
  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) return json({ error: 'No API key configured' }, { status: 500 });

  let body;
  try { body = await req.json(); } catch { return json({ error: 'Invalid JSON' }, { status: 400 }); }

  const { userId, plan, markers, cycleStartedAt, mealStyle, additionalGoal } = body || {};
  if (!Array.isArray(markers) || markers.length === 0) return json({ flags: [] });
  if (!cycleStartedAt) return json({ flags: [] }); // no active protocol to watch against

  if (userId) {
    const r = await rateLimit({ userId, endpoint: 'protocol-watch', limit: plan === 'pro' ? 100 : 10, windowHours: 24 });
    if (!r.ok) return json({ flags: [], rateLimited: true });
  }

  const numericFlags = detectFlags(markers, cycleStartedAt);
  if (numericFlags.length === 0) return json({ flags: [] });

  // Cache the narrative — the arithmetic above is free, but the Claude call isn't,
  // and the input (marker set + protocol) doesn't change between page loads.
  const markerHash = await hashMarkers(markers);
  const cacheKey = await sha256(`protocol-watch|${cycleStartedAt}|${mealStyle || 'none'}|${markerHash}`);
  const cached = await sbSelect('personalised_cache', `cache_key=eq.${cacheKey}&select=result,hits&limit=1`);
  if (cached && cached.length > 0) {
    sbUpdate('personalised_cache', `cache_key=eq.${cacheKey}`, { hits: (cached[0].hits || 0) + 1, last_hit_at: new Date().toISOString() }).catch(() => {});
    return json(cached[0].result, { headers: { 'x-cache': 'HIT' } });
  }

  const cachedInstructions = `You write short, direct, no-hedging health alerts for Aellux. You will be given markers that have moved consistently in the WRONG direction since the person started their current protocol, with the exact dates and values already computed — do not invent, estimate, or add any numbers beyond what's given.

For EACH flagged marker, write ONE tight alert (2-3 sentences max):
- State the fact plainly: marker name, baseline value/date, current value/date, the protocol name and start date.
- If severity is "physician": say plainly this warrants a doctor conversation this week. Do not suggest a supplement or lifestyle tweak as if it's sufficient on its own — name that a physician conversation is the primary next step, and give a specific reason (e.g. sustained magnitude, established risk threshold) if evident from the marker.
- If severity is "protocol": name the most likely dietary/protocol lever driving it (e.g. saturated fat load if the protocol is animal-based/keto/carnivore) and suggest a specific adjustment — but if the percentage change is large, still note that a doctor conversation is reasonable too.
- Never say "consult your doctor" as a throwaway hedge — only say it when severity is "physician", and when you do, mean it as the main point, not a disclaimer.
- No markdown, no bullet points, plain sentences.

Return ONLY valid JSON:
{"flags":[{"marker":"name","severity":"physician|protocol","alert":"the 2-3 sentence alert text"}]}`;

  const dynamicData = `Protocol: ${mealStyle || 'current protocol'}${additionalGoal ? ` (goal: ${additionalGoal})` : ''}, started ${cycleStartedAt.slice(0, 10)}.

Flagged markers (numeric analysis already done — use these exact numbers):
${numericFlags.map(f => `- ${f.marker}: was ${f.baseline_value}${f.unit} on ${f.baseline_date} (before protocol), now ${f.latest_value}${f.unit} on ${f.latest_date} — ${f.pct_change}% worse, across ${f.readings_since_start} readings since starting, still worsening as of the latest reading. Severity: ${f.severity}.`).join('\n')}`;

  try {
    const { text } = await callClaude({
      apiKey, model: 'claude-haiku-4-5-20251001', maxTokens: 900,
      cachedText: cachedInstructions, dynamicText: dynamicData,
    });
    let parsed;
    try {
      const clean = text.replace(/```json|```/g, '').trim();
      parsed = JSON.parse(clean);
    } catch {
      // Fall back to the numeric facts alone if the model output doesn't parse —
      // better to show the honest numbers than to show nothing.
      parsed = { flags: numericFlags.map(f => ({
        marker: f.marker, severity: f.severity,
        alert: `${f.marker} moved from ${f.baseline_value}${f.unit} (${f.baseline_date}) to ${f.latest_value}${f.unit} (${f.latest_date}) — ${f.pct_change}% worse since starting ${mealStyle || 'your protocol'} on ${cycleStartedAt.slice(0, 10)}.`,
      })) };
    }
    // Merge numeric detail back in so the frontend has both the narrative and the raw numbers
    const merged = { flags: parsed.flags.map(pf => ({ ...numericFlags.find(nf => nf.marker === pf.marker), ...pf })) };

    sbUpsert('personalised_cache', { cache_key: cacheKey, type: 'protocol_watch', result: merged, hits: 0, created_at: new Date().toISOString() }, 'cache_key').catch(() => {});
    if (userId) logUsage(userId, 'protocol-watch').catch(() => {});
    return json(merged, { headers: { 'x-cache': 'MISS' } });
  } catch (err) {
    // Never fail silently on something this important — fall back to the numeric
    // facts alone rather than showing nothing if the AI narrative call breaks.
    return json({ flags: numericFlags.map(f => ({
      marker: f.marker, severity: f.severity,
      alert: `${f.marker} moved from ${f.baseline_value}${f.unit} (${f.baseline_date}) to ${f.latest_value}${f.unit} (${f.latest_date}) — ${f.pct_change}% worse since starting ${mealStyle || 'your protocol'} on ${cycleStartedAt.slice(0, 10)}.`,
    })) });
  }
}
